import jsPDF from "jspdf";

export default function ResumeResult({
  analysis,
}) {

  console.log("ANALYSIS DATA:", analysis);

  if (!analysis) {
    return (
      <p>No data available</p>
    );
  }

  const result = analysis?.data || {};

const {
  score = 0,
  matchedSkills = [],
  missingSkills = [],
  suggestions = [],
  aiFeedback = "No AI feedback available",
} = result;

 
  const downloadPDF = () => {

    const doc = new jsPDF();

  
    doc.setFontSize(24);

    doc.setTextColor(
      79,
      70,
      229
    );

    doc.text(
      "Resume Analysis Report",
      20,
      25
    );

   
    doc.setDrawColor(200);

    doc.line(
      20,
      32,
      190,
      32
    );


    doc.setFontSize(18);

    doc.setTextColor(
      0,
      0,
      0
    );

    doc.text(
      `ATS Score: ${score}%`,
      20,
      50
    );

  
    doc.setFontSize(16);

    doc.setTextColor(
      34,
      197,
      94
    );

    doc.text(
      "Matched Skills",
      20,
      70
    );

    doc.setFontSize(12);

    doc.setTextColor(
      0,
      0,
      0
    );

    matchedSkills.forEach(
      (skill, index) => {

        doc.text(
          `• ${skill}`,
          30,
          80 + index * 8
        );
      }
    );

    
    let missingY =
      90 +
      matchedSkills.length * 8;

    doc.setFontSize(16);

    doc.setTextColor(
      239,
      68,
      68
    );

    doc.text(
      "Missing Skills",
      20,
      missingY
    );

    doc.setFontSize(12);

    doc.setTextColor(
      0,
      0,
      0
    );

    missingSkills.forEach(
      (skill, index) => {

        doc.text(
          `• ${skill}`,
          30,
          missingY +
            10 +
            index * 8
        );
      }
    );

    
    let feedbackY =
      missingY +
      20 +
      missingSkills.length * 8;

    doc.setFontSize(16);

    doc.setTextColor(
      79,
      70,
      229
    );

    doc.text(
      "AI Feedback",
      20,
      feedbackY
    );

    doc.setFontSize(12);

    doc.setTextColor(
      0,
      0,
      0
    );

    const splitFeedback =
      doc.splitTextToSize(
        aiFeedback.replace(
          /\*\*/g,
          ""
        ),
        160
      );

    doc.text(
      splitFeedback,
      20,
      feedbackY + 10
    );


    doc.setFontSize(10);

    doc.setTextColor(120);

    doc.text(
      "Generated by Resume Analyzer",
      20,
      285
    );

    doc.save(
      "resume-analysis-report.pdf"
    );
  };

  return (

    <section
  id="features"
  className="space-y-8 scroll-mt-24"
>

     
      <div className="text-center">

        <h2 className="text-4xl font-bold text-gray-900">
          Resume Analysis Result
        </h2>

        <p className="text-gray-600 mt-3">
          AI-powered ATS evaluation and skill analysis
        </p>

      </div>

     
      <div className="bg-white/80 backdrop-blur-xl rounded-3xl p-8 shadow-xl border border-white/40">

        <h3 className="text-2xl font-bold text-gray-900 mb-6">
          ATS Score
        </h3>

        <div className="w-full bg-gray-200 rounded-full h-5 overflow-hidden">

          <div
            className={`h-5 rounded-full transition-all duration-700 ${
              score > 75
                ? "bg-green-500"
                : score > 50
                ? "bg-yellow-500"
                : "bg-red-500"
            }`}
            style={{
              width: `${score}%`,
            }}
          ></div>

        </div>

        <p
          className={`mt-4 text-3xl font-bold ${
            score > 75
              ? "text-green-600"
              : score > 50
              ? "text-yellow-600"
              : "text-red-600"
          }`}
        >
          {score}%
        </p>

      </div>

   
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">

      
        <div className="bg-white/80 backdrop-blur-xl rounded-3xl p-8 shadow-xl border border-white/40">

          <h3 className="text-2xl font-bold text-gray-900 mb-6">
            Matching Skills
          </h3>

          <div className="flex flex-wrap gap-3">

            {matchedSkills.length >
            0 ? (

              matchedSkills.map(
                (
                  skill,
                  index
                ) => (

                  <span
                    key={index}
                    className="px-4 py-2 bg-green-100 text-green-700 rounded-full font-medium"
                  >
                    {skill}
                  </span>
                )
              )

            ) : (

              <p className="text-gray-500">
                No matched skills
                found
              </p>
            )}

          </div>

        </div>

       
        <div className="bg-white/80 backdrop-blur-xl rounded-3xl p-8 shadow-xl border border-white/40">

          <h3 className="text-2xl font-bold text-gray-900 mb-6">
            Missing Skills
          </h3>

          <div className="flex flex-wrap gap-3">

            {missingSkills.length >
            0 ? (

              missingSkills.map(
                (
                  skill,
                  index
                ) => (

                  <span
                    key={index}
                    className="px-4 py-2 bg-red-100 text-red-600 rounded-full font-medium"
                  >
                    {skill}
                  </span>
                )
              )

            ) : (

              <p className="text-gray-500">
                No missing skills
                found
              </p>
            )}

          </div>

        </div>

      </div>

   
      <button
        onClick={downloadPDF}
        className="px-6 py-3 bg-gradient-to-r from-indigo-600 to-purple-600 text-white rounded-xl font-semibold hover:scale-105 transition duration-300 shadow-lg"
      >
        Download PDF Report
      </button>

     
      <div className="bg-gradient-to-br from-indigo-600 to-purple-600 rounded-3xl p-8 shadow-2xl text-white">

        <h3 className="text-2xl font-bold mb-5">
          AI Resume Feedback
        </h3>

        <div className="space-y-4 text-gray-700 leading-relaxed">

          {aiFeedback
            .split("\n")
            .filter(
              (line) =>
                line.trim() !== ""
            )
            .map(
              (line, index) => (

                <div
                  key={index}
                  className="bg-indigo-50 border border-indigo-100 rounded-2xl p-5"
                >
                  {line.replace(
                    /\*\*/g,
                    ""
                  )}
                </div>
              )
            )}

        </div>

      </div>

    </section>
  );
}